version: "3.9"

networks:
  web-app:
    driver: bridge

services:
  database:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "todolist_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app-data:/var/lib/postgresql/data
    networks:
      - web-app
  
  backend:
    image: backend
    depends_on:
      - "database"
    container_name: backend
    ports:
      - "5000:80"
    build:
      context: ./ToDoList.Backend
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Port=5432;Database=todolist_db;User Id=postgres;Password=postgres
      - ASPNETCORE_URLS=http://+:80
    networks:
      - web-app
  
  frontend:
    image: frontend
    container_name: frontend
    ports:
      - "5001:80"
    build:
      context: ./ToDoList.Frontend
      dockerfile: Dockerfile
    networks:
      - web-app
volumes:
  app-data:
